### ISSUE TITLE
[vue-router] Failed to resolve async component default: Error: Cannot find module '@/views/sysuser/index'

### ISSUE THREAD

**Issue by ClawHub** [wenjianzhang/go-admin-ui#13]
项目运行起来之后，点击菜单后控制台报错，且跳转没有反应，我试着升级了node版本到v12.16.2后，重新编译运行，也失败。

**Comment by ClawHub** [comment]
vue-router.esm.js:1897 Error: Cannot find module '@/views/sysuser/index'
    at webpackEmptyContext (index.js:39)
    at permission.js:94

**Comment by eippbx** [comment]
同问

**Comment by aixwlove** [comment]
应该是原框架有个依赖出问题了，据说是webpack的原因，具体原因不详。原作者也没有更新。
我这个找到个解决办法
store/modules/permission.js
`export const loadView = (view) => { // 路由懒加载
  return () => impot(`@/views${view}`)
}`
修改为
`export const loadView = (view) => { // 路由懒加载
  return (resolve) => require([`@/views${view}`], resolve)
}`
就可以了
[https://github.com/PanJiaChen/vue-element-admin/issues/3129](url)

**Comment by ClawHub** [comment]
@aixwlove 6666!我修改成：export const loadView = (view) => {
  // 路由懒加载
  return (resolve) => require([`@/views${view}`], resolve)
} 之后就好了
