### ISSUE TITLE
自动生成代码优化

### ISSUE THREAD

**Issue by linland** [wenjianzhang/go-admin-ui#41]
1.新增或修改页如果为选择框，值无法动态获取
2.建议增加时间属性选择

**Comment by wenjianzhang** [comment]
选择框和下拉框需要和数据字典配合使用

**Comment by linland** [comment]
是配合使用的，新增或修改页面选择项是demo

**Comment by wenjianzhang** [comment]
dict 对应的 struct 字段 定义的时候把类型定义成string就好了

**Comment by wenjianzhang** [comment]
感谢您的建议，该问题已经修复，谢谢！
