### ISSUE TITLE
dialog 过长时上面的内容不可见

### ISSUE THREAD

**Issue by MoonBegonia** [wenjianzhang/go-admin-ui#67]
dialog 长度超过屏幕长度时上半部分的内容不可见，滑动条显示到顶同样不可见
![image](https://user-images.githubusercontent.com/26798347/91114432-7b96b000-e6ba-11ea-9587-51f6ccd17bf5.png)

**Comment by ahKevinXy** [comment]
这个是css 问题,可惜我不会写css

**Comment by MoonBegonia** [comment]
@ahKevinXy 我会写而且我已经写好了呢

**Comment by hjldev** [comment]
> @ahKevinXy 我会写而且我已经写好了呢

怎么解决的，求方案

**Comment by MoonBegonia** [comment]
> > @ahKevinXy 我会写而且我已经写好了呢
> 
> 怎么解决的，求方案

![image](https://user-images.githubusercontent.com/26798347/92921658-0a4f4f00-f467-11ea-8e1c-031240e4f410.png)
这删除看看

**Comment by hjldev** [comment]
> > > @ahKevinXy 我会写而且我已经写好了呢
> > 
> > 
> > 怎么解决的，求方案
> 
> ![image](https://user-images.githubusercontent.com/26798347/92922008-ac6f3700-f467-11ea-8599-a24e3f092498.png)
> 
> 这删除看看,然后加个底部边距就行了
> src/styles/admin.scss:
> 
> ```css
> .el-dialog {
> margin-bottom: 8vh !important;
>  }
> ```

删除掉.el-dialog__wrapper这个样式解决了，谢谢啦
